import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import ThemeProviderWrapper from "@/components/ui/ThemeProviderWrapper" // path to wrapper
import Nav from "@/components/Navbar"

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] })
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProviderWrapper>
          <Nav />
           <main className="pt-20 px-4 md:px-8"></main>
          {children}
        </ThemeProviderWrapper>
      </body>
    </html>
  )
}