import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from "@/components/ui/ThemeProviderWrapper";
import Nav from "@/components/Navbar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* 👇 Enable smooth scrolling globally */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth bg-background text-foreground`}
      >
        <ThemeProviderWrapper>
          <Nav />
          {/* 👇 Add proper top padding so content isn’t hidden under Nav */}
          <main className="pt-15 min-h-screen">
            {children}
          </main>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
